### PR TITLE
DLS-9802 - UI test date fix

### PR DESCRIPTION
**Pull request by TomRafferty**

### CODE REVIEW

**Comment by johno1985** [comment]
Can we address some of the PR bot comments?

**Comment by TomRafferty** [comment]
> * BackendModule

yeah haha just noticed them was already working on it 😆

**Comment by mahesh-hmrc** [comment]
Can we add test scope for the last 2 dependencies aswell, as per the bot comment ?

**Review by mahesh-hmrc — COMMENTED** [review]
LGTM!

**Comment by TomRafferty** [comment]
rebuild

**Comment by TomRafferty** [comment]
> * `uk.gov.hmrc.stub-data-generator` in [project/AppDependencies.scala](https://github.com/hmrc/cgt-property-disposals-stubs/blob/DLS-9802%2FTom%2FUI-test-date-fix/project/AppDependencies.scala#L15) is not limited to test scope but pulls in test dependencies

As pointed out by @mahesh-hmrc we can't follow through with this PR bot request

**Review by mahesh-hmrc — APPROVED** [review]

**Pull request merged**
